//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: credentials.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// There is a single API which returns the credentials available for the given user id.
///
/// There is no registration needed, just generate a random UUID, and use that, the server
/// will generate credentials automatically for it.
///
/// Usage: instantiate `Io_Iohk_Test_Protos_CredentialsServiceClient`, then call methods of this protocol to make API calls.
internal protocol Io_Iohk_Test_Protos_CredentialsServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Io_Iohk_Test_Protos_CredentialsServiceClientInterceptorFactoryProtocol? { get }

  func getCredentials(
    _ request: Io_Iohk_Test_Protos_GetCredentialsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Io_Iohk_Test_Protos_GetCredentialsRequest, Io_Iohk_Test_Protos_GetCredentialsResponse>
}

extension Io_Iohk_Test_Protos_CredentialsServiceClientProtocol {
  internal var serviceName: String {
    return "io.iohk.test.protos.CredentialsService"
  }

  /// Unary call to GetCredentials
  ///
  /// - Parameters:
  ///   - request: Request to send to GetCredentials.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getCredentials(
    _ request: Io_Iohk_Test_Protos_GetCredentialsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Io_Iohk_Test_Protos_GetCredentialsRequest, Io_Iohk_Test_Protos_GetCredentialsResponse> {
    return self.makeUnaryCall(
      path: "/io.iohk.test.protos.CredentialsService/GetCredentials",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetCredentialsInterceptors() ?? []
    )
  }
}

internal protocol Io_Iohk_Test_Protos_CredentialsServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'getCredentials'.
  func makeGetCredentialsInterceptors() -> [ClientInterceptor<Io_Iohk_Test_Protos_GetCredentialsRequest, Io_Iohk_Test_Protos_GetCredentialsResponse>]
}

internal final class Io_Iohk_Test_Protos_CredentialsServiceClient: Io_Iohk_Test_Protos_CredentialsServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Io_Iohk_Test_Protos_CredentialsServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the io.iohk.test.protos.CredentialsService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Io_Iohk_Test_Protos_CredentialsServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// There is a single API which returns the credentials available for the given user id.
///
/// There is no registration needed, just generate a random UUID, and use that, the server
/// will generate credentials automatically for it.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Io_Iohk_Test_Protos_CredentialsServiceProvider: CallHandlerProvider {
  var interceptors: Io_Iohk_Test_Protos_CredentialsServiceServerInterceptorFactoryProtocol? { get }

  func getCredentials(request: Io_Iohk_Test_Protos_GetCredentialsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Io_Iohk_Test_Protos_GetCredentialsResponse>
}

extension Io_Iohk_Test_Protos_CredentialsServiceProvider {
  internal var serviceName: Substring { return "io.iohk.test.protos.CredentialsService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetCredentials":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Io_Iohk_Test_Protos_GetCredentialsRequest>(),
        responseSerializer: ProtobufSerializer<Io_Iohk_Test_Protos_GetCredentialsResponse>(),
        interceptors: self.interceptors?.makeGetCredentialsInterceptors() ?? [],
        userFunction: self.getCredentials(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Io_Iohk_Test_Protos_CredentialsServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'getCredentials'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetCredentialsInterceptors() -> [ServerInterceptor<Io_Iohk_Test_Protos_GetCredentialsRequest, Io_Iohk_Test_Protos_GetCredentialsResponse>]
}
